### ISSUE TITLE
ASCII/UTF-8 problems

### ISSUE THREAD

**Issue by TheFiZi** [CloudBotIRC/CloudBotLegacy#166]
CloudBot will randomly fail to respond to .twitter and .google commands. I'm no expert but I think it's a ASCII/UTF-8 problem. 

Shouldn't the entire bot just use UTF-8 at this point?

Example:

```
16:55:37 #gaming <evildoer> .g compatible
Unhandled exception in thread started by <function run at 0x7fd9e82d7b90>
Traceback (most recent call last):
  File "core/main.py", line 73, in run
    input.reply(unicode(out))
  File "core/main.py", line 26, in reply
    conn.msg(target, "({}) {}".format(nick, message.encode('utf-8')))
  File "core/irc.py", line 209, in msg
    self.cmd("PRIVMSG", [target, text])
  File "core/irc.py", line 220, in cmd
    self.send(command + ' ' + ' '.join(map(censor, params)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 246: ordinal not in range(128)
```

**Comment by TheFiZi** [comment]
This has been resolved in the last update to the Google plugin.
