### ISSUE TITLE
XML error with stock.py

### ISSUE THREAD

**Issue by TheFiZi** [CloudBotIRC/CloudBotLegacy#173]
18:27:19 #gaming <FiZi> .stock bbry

Unhandled exception in thread started by <function run at 0x7f2dd20dc410>
Traceback (most recent call last):
  File "core/main.py", line 70, in run
    out = func(input.inp)
  File "plugins/stock.py", line 12, in stock
    parsed = http.get_xml(url, stock=inp)
  File "plugins/util/http.py", line 47, in get_xml
    return etree.fromstring(get(_args, *_kwargs))
  File "lxml.etree.pyx", line 2997, in lxml.etree.fromstring (src/lxml/lxml.etree.c:63276)
  File "parser.pxi", line 1617, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:93691)
  File "parser.pxi", line 1495, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:92490)
  File "parser.pxi", line 1011, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:89130)
  File "parser.pxi", line 577, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:84831)
  File "parser.pxi", line 676, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:85936)
  File "parser.pxi", line 616, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:85258)
lxml.etree.XMLSyntaxError: StartTag: invalid element name, line 1, column 2

**Comment by dmptrluke** [comment]
The API was removed, moved to a new API with #12e2a445d7819838af48af1d3de81255c59ba72f
