### ISSUE TITLE
.stock kinda broken?

### ISSUE THREAD

**Issue by TheFiZi** [CloudBotIRC/CloudBotLegacy#203]
```
21:42:03 #gaming <FiZi> .stock bbry
Unhandled exception in thread started by <function run at 0x1501500>
Traceback (most recent call last):
  File "core/main.py", line 70, in run
    out = func(input.inp)
  File "plugins/stock.py", line 10, in stock
    quote = web.query(query, {"symbol": sym}).one()
  File "/data/apps/sa_ircBot/python/lib/python2.7/site-packages/yql/__init__.py", line 84, in one
    return rows[0]
IndexError: list index out of range


21:43:23 #gaming <FiZi> .stock bbry
{u'YearLow': u'5.44', u'MarketCapitalization': u'5.095B', u'DaysHigh': u'10.05', 'color': '5', u'symbol': u'BBRY', u'DaysLow': u'9.695', u'Volume': u'15732769', u'StockExchange': u'NasdaqNM', 'PercentChange': -1.3052208835341363, u'DaysRange': u'9.695 - 10.05', u'AverageDailyVolume': u'24814900', u'LastTradePriceOnly': u'9.83', u'YearHigh': u'17.22', u'Symbol': u'BBRY', u'Change': u'-0.13', u'Name': u'BlackBerry Limite'}
>>> u'PRIVMSG #gaming :(FiZi) \x02BlackBerry Limite\x02 (\x02BBRY\x02) - 9.83 \x035-0.13 (-1.31%)\x03 Day Range: 9.695 - 10.05 MCAP: 5.095B'


21:43:39 #gaming <FiZi> .stock goog
Unhandled exception in thread started by <function run at 0x1501500>
Traceback (most recent call last):
  File "core/main.py", line 70, in run
    out = func(input.inp)
  File "plugins/stock.py", line 10, in stock
    quote = web.query(query, {"symbol": sym}).one()
  File "/data/apps/sa_ircBot/python/lib/python2.7/site-packages/yql/__init__.py", line 84, in one
    return rows[0]
IndexError: list index out of range
```

**Comment by dmptrluke** [comment]
Well, it seems to work fine for me on my test bot :/

**Comment by TheFiZi** [comment]
Seems hit or miss. It usually works but that day we had intermittent results.

Will close for now and re-open if I can get better data for you.
