### ISSUE TITLE
Bot exception when experiencing a .net split

### ISSUE THREAD

**Issue by GenPage** [CloudBotIRC/CloudBotLegacy#298]
``` bash
Unhandled exception in thread started by <bound method crlf_tcp.run of <__main__.crlf_tcp object at 0x7f3dd12e3610>>
Traceback (most recent call last):
  File "core/irc.py", line 47, in run
    self.socket.connect((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.timeout: timed out
```

Exception when the bot experienced a .net split

**Comment by Pyker** [comment]
Apparently this is a rather old bug: https://github.com/ClouDev/CloudBot/issues/49
