### ISSUE TITLE
Plugins won't run

### ISSUE THREAD

**Issue by neersighted** [CloudBotIRC/CloudBotLegacy#6]
```
$ neer@chrisgward (~/.irssi/scripts/autorun): python2.7 ~/neerbot/bot.py
Loading plugins
Traceback (most recent call last):
  File "core/reload.py", line 89, in reload
    eval(code, namespace)
  File "plugins/youtube.py", line 8, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/local/lib/python2.7/locale.py", line 531, in setlocale
    return _setlocale(category, locale)
Error: unsupported locale setting
Traceback (most recent call last):
  File "core/reload.py", line 87, in reload
    code = compile(open(filename, 'U').read(), filename, 'exec')
  File "plugins/factoids.py", line 71
    return
         ^
IndentationError: expected an indented block
```

Seems some stuff STILL won't run. Any ideas?

**Comment by neersighted** [comment]
Hmm, thanks for adding the note on installing enchant.  I _will_ eventually finish my controler
